# Generated by Django 6.0.2 on 2026-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('gold', models.FloatField()),
                ('silver', models.FloatField()),
                ('platinum', models.FloatField()),
                ('diamond', models.FloatField()),
            ],
        ),
    ]
